server:
  port: ${PORT:8080}

spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${HOST_DB:localhost}:${PORT_DB:7777}/${NAME_DB:geoquiz}?autoReconnect=true&useSSL=false
    password: ${PASSWORD_DB:geoquiz}
    username: ${USER_DB:geoquiz}

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # FIXME ddl-auto: update (prod) create-drop (dev).
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true